# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.INFO }}

          # Options
          user: mmichaell23
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Singapore
          plugin_anilist: yes
          plugin_anilist_limit: 22
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_languages: yes
          plugin_languages_aliases: C++, Java
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_music: yes
          plugin_music_limit: 10
          plugin_music_mode: top
          plugin_music_playlist: ${{ secrets.SPOTIFY_PLAYLIST }}
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_user: .user.login
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars
