# Visit https://github.com/lowlighter/metrics#-documentation for full reference

  # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional,           if you want to include private repositories)
      
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

    - name: User
      uses: lowlighter/metrics@latest
      with: 
        filename: user.svg
        token: ${{ secrets.INFO }}
        output_action: gist
        committer_gist: ${{ secrets.GIST }}
        user: mmichaell23
        template: classic
        base: header
        plugin_introduction: yes
        plugin_introduction_title: yes
        plugin_followup: yes
        plugin_followup_archived: yes
        plugin_followup_indepth: yes
        plugin_followup_sections: repositories
        plugin_reactions: yes
        plugin_reactions_details: count
        plugin_reactions_display: relative
        plugin_reactions_limit: 200
        plugin_reactions_limit_discussions: 100
        plugin_reactions_limit_discussions_comments: 100
        plugin_reactions_limit_issues: 100
        plugin_achievements: yes
        plugin_achievements_display: compact
        
    - name: Info
      uses: lowlighter/metrics@latest
      with:
          filename: info.svg
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          token: ${{ secrets.INFO }}
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_recent_categories: markup, programming
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          
    - name: social
      uses: lowlighter/metrics@latest
      with:
          filename: social.svg
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          token: ${{ secrets.INFO }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_limit: 5
          plugin_anilist_limit_characters: 5
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters, reading
          plugin_anilist_shuffle: yes
          plugin_anilist_user: Sudo23
          plugin_music: yes
          plugin_music_limit: 10
          plugin_music_mode: top
          plugin_music_playlist: ${{ secrets.SPOTIFY_PLAYLIST }}
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_user: .user.login
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
  
    - name: fortune
      uses: lowlighter/metrics@latest
      with:
          filename: fortune.svg
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          token: ${{ secrets.INFO }}       
          base: ""   
          plugin_fortune: yes